setup backend
dar1ooo/schoolab-design-fiction pull request #6
Opened 2023-10-10 19:12 UTC by gianlucanaegeli

Title says it all.

2023-10-11 00:49 UTC, dar1ooo requested changes

2023-10-11 00:49 UTC, dar1ooo commented on backend/api/Controllers/ProjectController.cs
> +        try
chamer die exceptions ned über en globale exception handler irgendwie löse ?

2023-10-11 00:49 UTC, dar1ooo commented on backend/api/Controllers/StepController.cs
> +    public IActionResult GetStep(Guid stepId, Guid projectId)
chamer zwei parameter bimene get mitgeh ? währ da ned post maybe gschieder, dasmer zwei parameter ageh chan ?

2023-10-11 00:49 UTC, dar1ooo commented on backend/api/Interfaces/IContentService.cs
> +    public List<MongoDbContent>? GetAll();
macht da nullable sinn ?

2023-10-11 00:49 UTC, dar1ooo commented on backend/api/Interfaces/IManageDto.cs
> +    public List<StepNameDto>? GetProjectStepNames(List<Guid>? stepsId);
macht da nullable sinn ?

2023-10-11 00:49 UTC, dar1ooo commented on backend/api/Interfaces/IManageDto.cs
> +    public List<UserDto>? GetParticipants(List<Guid>? participantsId);
macht da nullable sinn ?

2023-10-11 00:49 UTC, dar1ooo commented on backend/api/Interfaces/IProjectService.cs
> +    public List<Guid>? GetAllIds();
macht da nullable sinn ?

2023-10-11 00:49 UTC, dar1ooo commented on backend/api/Interfaces/IStepService.cs
> +    public List<MongoDbStep>? GetAll();
macht da nullable sinn ?

2023-10-11 00:49 UTC, dar1ooo commented on backend/api/Interfaces/IUserService.cs
> +    public List<MongoDbUser>? GetAll();
macht da nullable sinn ?

2023-10-12 16:34 UTC, gianlucanaegeli commented on backend/api/Interfaces/IUserService.cs
> +    public List<MongoDbUser>? GetAll();
chund drufah, wenns kein einzige user git aber du die würsch welle azeige scho ja, suscht gits eifach en exception und mit de jetztige Lösig chönntsch säge no user found im ui oder so

2023-10-12 16:35 UTC, gianlucanaegeli commented on backend/api/Interfaces/IStepService.cs
> +    public List<MongoDbStep>? GetAll();
si, wenn es project erstellt hesch und no kei step zugwise isch

2023-10-12 17:10 UTC, gianlucanaegeli commented on backend/api/Controllers/ProjectController.cs
> +        try
maybe later on but not necessary for first merge

2023-10-13 16:48 UTC, merged